### ISSUE TITLE
proper logging system

### ISSUE THREAD

**Issue by helgrima** [tahtituho/shader-system#6]
currently logging happens on console, but more proper way would be using only one window and maybe slicing some part of it for logging.

**Comment by Colho** [comment]
There  is a function for logging to a file, this should be finalized

**Comment by helgrima** [comment]
finalized in 87968c44160a787f1e5c244a275337e3c17ab65e 55a3c544d74f974f53c986963ab558043ccb3210 8f3079756abc0ffaf2733a91d835c4d177099d6a
