### ISSUE TITLE
release mode

### ISSUE THREAD

**Issue by helgrima** [tahtituho/shader-system#9]
support for release mode where rocket client is not needed, but demo is synced with rocket file and it will auto run on fullscreen
related #7

**Comment by helgrima** [comment]
configuration json already contains path to rocket file

**Comment by Colho** [comment]
TODO list for this issue:
- [x] Get rid of CMD on startup
- [x] Redirect CMD messages to a file in debug mode
- [X] Add a possibility to release mode in configuration.json
- [X] Automatic fullscreen on release mode
- [X] ESC to close the scene
- [X] Hide cursor in release mode
- [X] Music starts automatically, and sync comes from file without rocket client

**Comment by Colho** [comment]
Release mode is almost final. Hiding CMD and redirecting error messages to file is missing.

**Comment by helgrima** [comment]
TODO list complete
